### ISSUE TITLE
Adding node-polyfill-webpack-plugin breaks semi-common "msgpack" npm module

### ISSUE THREAD

**Issue by mcclure** [Richienb/node-polyfill-webpack-plugin#11]
**Summary:** Using the npm package @msgpack/msgpack with node-polyfill-webpack-plugin fails with "The request 'process/browser' failed to resolve only because it was resolved as fully specified".

**Context:** I have a web app. I upgraded from Webpack 4 to 5. This broke some npm dependencies that relied on node-builtin modules. I installed node-polyfill-webpack-plugin to fix this. This broke a different npm dependency (msgpack)

**Repro:**
I have a minimal [test repo](https://github.com/mcclure/ts-hello-bug/tree/mspack-webpack-compat) here. To test with it, run `npm install && npx webpack` and a minimal web app will be built into `site/`.

In this repro, the commit `2f5f39b8` is a working web app using Webpack 4 and msgpack.  `213e2608` is a working web app upgraded to Webpack 5 and msgpack— the breakage does not occur until I try to add node-polyfill-webpack-plugin. `51fbc8fec` (HEAD) adds node-polyfill-webpack-plugin and configures it as in "Usage" in the README. This results in the error:

```
ERROR in ./node_modules/@msgpack/msgpack/dist.es5+esm/utils/utf8.mjs 2:38-45
Module not found: Error: Can't resolve 'process/browser' in '/Users/mcc/work/h/ts-hello/node_modules/@msgpack/msgpack/dist.es5+esm/utils'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
resolve 'process/browser' in '/Users/mcc/work/h/ts-hello/node_modules/@msgpack/msgpack/dist.es5+esm/utils'
  Parsed request is a module
  using description file: /Users/mcc/work/h/ts-hello/node_modules/@msgpack/msgpack/package.json (relative path: ./dist.es5+esm/utils)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/mcc/work/h/ts-hello/node_modules/@msgpack/msgpack/dist.es5+esm/utils/node_modules doesn't exist or is not a directory
      /Users/mcc/work/h/ts-hello/node_modules/@msgpack/msgpack/dist.es5+esm/node_modules doesn't exist or is not a directory
      /Users/mcc/work/h/ts-hello/node_modules/@msgpack/msgpack/node_modules doesn't exist or is not a directory
      /Users/mcc/work/h/ts-hello/node_modules/@msgpack/node_modules doesn't exist or is not a directory
      /Users/mcc/work/h/ts-hello/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/mcc/work/h/ts-hello/node_modules
        existing directory /Users/mcc/work/h/ts-hello/node_modules/process
          using description file: /Users/mcc/work/h/ts-hello/node_modules/process/package.json (relative path: .)
            using description file: /Users/mcc/work/h/ts-hello/node_modules/process/package.json (relative path: ./browser)
              Field 'browser' doesn't contain a valid alias configuration
              /Users/mcc/work/h/ts-hello/node_modules/process/browser doesn't exist
      /Users/mcc/work/h/node_modules doesn't exist or is not a directory
      /Users/mcc/work/node_modules doesn't exist or is not a directory
      /Users/mcc/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./node_modules/@msgpack/msgpack/dist.es5+esm/Decoder.mjs 59:0-86 636:30-52 637:21-33 640:21-33
 @ ./node_modules/@msgpack/msgpack/dist.es5+esm/index.mjs 8:0-71 10:0-63 10:0-63
 @ ./src/index.tsx 19:16-43

webpack 5.38.1 compiled with 1 error in 3975 ms
```

**Expected behavior:** I should be able to recreate Webpack 4 behavior in Webpack 5+node-polyfill-webpack-plugin.

**Note:** It is possible this is not a bug, NPWP's behavior is correct, and I would get my expected behavior if I properly configured `excludeAliases`. If so, I think this is a documentation issue, and I am filing a separate issue about that.

**Comment by fregante** [comment]
Identical issue, description, and possible solutions here: https://github.com/Raynos/global/issues/21

In short:

- either the publisher of each polyfill publishes them as CJS/ESM combos
- or the importer, in this case `node-polyfill-webpack-plugin`, uses an ESM-compatible entry point, like `'process/browser.js'` instead of `'process/browser'`

**Comment by Richienb** [comment]
Maybe we could just upgrade this package to use ESM instead of CommonJS?

**Comment by fregante** [comment]
I don’t think that's the issue. The problem is that this package redirects `import 'process/browser'` to a package that cannot be imported that way. The ESM change needs to be in the `process` package itself, there's nothing this plugin can do, I think, since Webpack complains about the dependency, not the plugin

**Comment by Richienb** [comment]
> uses an ESM-compatible entry point, like 'process/browser.js' instead of 'process/browser'

Alright, let's do this then.

**Comment by Richienb** [comment]
https://github.com/Richienb/node-polyfill-webpack-plugin/pull/15
