### ISSUE TITLE
Documentation should specify how to reproduce Webpack 4 behavior

### ISSUE THREAD

**Issue by mcclure** [Richienb/node-polyfill-webpack-plugin#12]
I am trying to upgrade from Webpack 4 to Webpack 5. Because Webpack 4 removes the node polyfills, this causes breakage with various modules in npm I am using. My understanding is node-polyfill-webpack-plugin fixes this.

However, on installing Webpack 5 + node-polyfill-webpack-plugin, I see various signs that I have reproduced something *slightly* different from Webpack 4. My evidence of this is:

- Issue #11
- Checking google I find much discussion about whether or not to excludeAlias "console" when using node-polyfill-webpack-plugin. I don't understand this.

The README contains a list of many modules, any of which are candidates for excludeAlias. But I don't know which modules Webpack 4 supplied, so I don't know what I have to exclude in order to reproduce webpack 4's module list. I don't know the technical background of this stuff and I'm confused.

I expect "reproduce Webpack 4 behavior/npm module compatibility in Webpack 5" is a common use case for node-polyfill-webpack-plugin. Therefore, my "**expected behavior**" is:

There should be text in the node-polyfill-webpack-plugin doc (the README) explaining exactly which `excludeAlias` values (or other configs) reproduce the behavior of Webpack 4. If null `excludeAlias` produces the module list used in Webpack 4, the docs should say that, for the benefit of the next person who gets confused the way I've got myself confused.

**Comment by Richienb** [comment]
By default, the aliases polyfilled should be exactly the same as Webpack 4. The `excludeAliases` option exists in case you want to exclude one of them from being included. https://github.com/Richienb/node-polyfill-webpack-plugin/issues/7

**Comment by mcclure** [comment]
Great, thanks.
The sentence you added to the README would have resolved the confusion I had yesterday, so I'm closing this.
This does however make #11 seem like it could be an actual bug.
