### ISSUE TITLE
[Feature Request] Allow specifying a root directory to resolve polyfill'ed modules against

### ISSUE THREAD

**Issue by dmnsgn** [Richienb/node-polyfill-webpack-plugin#13]
**Issue:**
At the moment, all resolution assumes the modules are installed alongside webpack.

The fallback configuration (https://webpack.js.org/configuration/resolve/#resolvefallback) allows absolute path to be specified: `path.resolve(__dirname, 'path/to/file.js')`. That's particularly useful if you run webpack programmatically and have the config in a different place than the codebase containing the polyfills.

**Feature Request:**

Add an option (`root`, `resolutionDir`, `base`, `notSureWhatsAGoodName`...) to specify the root. Either absolute or a function:
```js
const myDir = path.resolve(__dirname, 'somewhere')
new NodePolyfillPlugin({
  root: (polyfillName) => path.join(myDir, polyfillName)
  // or...
  root: myDir,
})
```

**Comment by Richienb** [comment]
> At the moment, all resolution assumes the modules are installed alongside webpack.

They are.

> That's particularly useful if you run webpack programmatically and have the config in a different place than the codebase containing the polyfills.

In that case, it could be better to just detect where `node-polyfill-webpack-plugin` is installed and resolve the absolute path relative to the `node_modules` directory it is installed in.

**Comment by dmnsgn** [comment]
Could replacing `assert: "assert",` with `assert: require.resolve("assert"),` etc. help achieve that instead of using `path`?
