### ISSUE TITLE
[Question] Is it possible to add extensions for the polyfill routes like `.js` and `.mjs`

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [Richienb/node-polyfill-webpack-plugin#14]
Thanks for the plugin 😄

I am trying to use this plugins inside a [docusaurus](https://docusaurus.io) project which uses webpack 5. 
So, i created a tiny wrapper around docusaurus, so i can inject this inside the webpack config.
https://github.com/JayaKrishnaNamburu/docusaurus-node-polyfills

But the problem is, one of the dependencies is using `process` but the package is configured as `esm` module with `type: module` in it's package.json field. You can find the config field here https://unpkg.com/browse/lezer@0.13.5/package.json

And since, the package is using `module` flag. And in node~14 which supports it. Needs the file extension to import the package and so started to throw error. Something like this

<img width="547" alt="Screenshot 2021-06-11 at 10 10 29 PM" src="https://user-images.githubusercontent.com/11075561/121725189-8e258d00-cb06-11eb-8fe5-02001dc6dbdd.png">

I am not sure, where this should be handled, should webpack do it. Or should the plugins which polyfills the node stuff should take care of the extensions etc 😄. Please close this, if not in the scope of repo.

**Comment by Richienb** [comment]
See https://github.com/Richienb/node-polyfill-webpack-plugin/issues/11#issuecomment-855385058

**Comment by JayaKrishnaNamburu** [comment]
Ah, this is a duplicate. So does adding process/browser.js solves this thing 🤔. I will take a look once it if fixes this
