### ISSUE TITLE
Can't resolve 'console-browserify'

### ISSUE THREAD

**Issue by targeral** [Richienb/node-polyfill-webpack-plugin#16]
My project is using pnpm and when using this plugin, the following error is reported：

`Module not found: Error: Can't resolve 'console-browserify' in '/Users/targeral/demo/pnpm/demo4/mwa/src`.

I need to configure the following in the .npmrc file for it to work properly. This configuration raises `console-browserify` to the top-level node_modules

```
public-hoist-pattern[]=console-browserify
```

I think I can only configure all the dependencies for this plugin in .npmrc for now.

I'd like to know if there is a better way or if it is compatible with pnpm

**Comment by Richienb** [comment]
We'll need to use `require.resolve` to get the absolute paths of each of the modules so it will always be findable.

**Comment by chengcyber** [comment]
I got a question here. Is it necessary to polyfill `console`?

**Comment by Richienb** [comment]
> Is it necessary to polyfill `console`?

Only if you want to perfectly replicate Webpack 4 behaviour. Otherwise, see [`excludeAliases`](https://github.com/Richienb/node-polyfill-webpack-plugin#excludealiases).
