### ISSUE TITLE
Polyfilled console is empty

### ISSUE THREAD

**Issue by nictownsend** [Richienb/node-polyfill-webpack-plugin#20]
Using the default plugin configuration, `console` appears to be polyfilled as an empty object.

One of my dependencies uses `uuid` which uses `util.deprecate` - but in `util` the `console` is simply an empty object so errors when it tries to call `console.error`

```
new NodePolyfillPlugin({
			excludeAliases: ["console"]
		}),
```
Appears to fix it.

**Comment by Ebukachuqz** [comment]
> Errors with polyfilling the console have been popping up a lot. I'm considering no longer polyfilling it by default any more. Thoughts?

Please do not polyfill it anymore. I still have issues with it presently
