### ISSUE TITLE
Trying to understand this plugin

### ISSUE THREAD

**Issue by TechAkayy** [Richienb/node-polyfill-webpack-plugin#24]
Hi there, 

Thanks for this plugin. Just want to understand, does this plugin, sets the config like this....  
 
```
		resolve: {
			fallback: {
				path: false,
				https: false,
				// ... etc
			},
		},
```

... or does it install all the necessary polyfills and sets the config like this: 

```
		resolve: {
			fallback: {
				path: require.resolve('path-browserify/'), 
				https: require.resolve('https-browserify/'), 
				// ... etc
			},
		},
```

Thanks in advance. I'm a newbie and caught up with migrating from webpack v4 to v5.

**Comment by Richienb** [comment]
It does the latter
