### ISSUE TITLE
Can't resolve 'fs' module

### ISSUE THREAD

**Issue by harshit3994** [Richienb/node-polyfill-webpack-plugin#29]
I tried bundling the library via webpack but it seems webpack does'nt seem to polyfill fs node module.Tried with both webpack5(where we need to polyfill explicitly).All core modules were polyfilled except fs.

Please let me know your thoughts about polyfilling fs module

**Comment by Richienb** [comment]
It is impossible to polyfill the `fs` module in the browser.
