### ISSUE TITLE
SharedArrayBuffer Warning

### ISSUE THREAD

**Issue by gueste** [Richienb/node-polyfill-webpack-plugin#4]
The nodeJS "util" dependency seems to trigger a warning when used in lastet Chrome 89 upwards.

```
types.js:333 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
./node_modules/util/support/types.js @ types.js:333
15:58:10.529 
```

A fix can look like this (taken from react): https://github.com/facebook/react/pull/20831

**Comment by Richienb** [comment]
Affected file: https://github.com/browserify/node-util/blob/master/support/types.js

**Comment by Richienb** [comment]
As it turns out, the script is already prepared to handle a lack of `SharedArrayBuffer` when Chrome 91 comes around. https://github.com/browserify/node-util/issues/58#issuecomment-801212833

**Comment by gueste** [comment]
Thank you so much for checking, even if the issue had nothing to do with your repository!
(Issue can be closed again if I accidentally re-open it with this comment)
