### ISSUE TITLE
[Feature Req]: Can we include `fs` module polyfill to the plugin?

### ISSUE THREAD

**Issue by AkshitAggarwal** [Richienb/node-polyfill-webpack-plugin#41]
This plugin is super helpful, so far most of the core modules are included as I can see. But I had to include the polyfill for `fs` module separately. Can we include that in the global plugin itself?

**Comment by Richienb** [comment]
Which fs polyfill is used?

**Comment by afonsojramos** [comment]
@Richienb there is no polyfill for `fs` in the browser, hence #45.

**Comment by Richienb** [comment]
@afonsojramos What's the user experience with using `'fs': false`?
Does it necessitate adding a note about it in the readme?

**Comment by afonsojramos** [comment]
The point of this repo is to facilitate polyfills, and since there is no polyfill for `fs`, we might as well set it to `false` to set it as an empty implementation. Even [some upgrade guides](https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a) of webpack v4 to v5 suggest it.
