### ISSUE TITLE
Implementing this plugin in Next.js makes .env variables unavailable.

### ISSUE THREAD

**Issue by odysseaspapadimas** [Richienb/node-polyfill-webpack-plugin#43]
I'm trying to replicate the object detection in [this](https://github.com/juanjaho/real-time-object-detection-web-app/blob/master/next.config.js) project and it uses this plugin but the thing is it makes .env variables unavailable making my app useless. 

This does not seem essential to my application but I have issues in production with loading the wasm files so I believe this plugin could possibly fix that so any help would be greatly appreciated.

Steps to reproduce: Clone that project and try to use an .env variable. Removing the plugin fixes the issue.

**Comment by Richienb** [comment]
Does this work?

```js
new NodePolyfillPlugin({excludeAliases: ['process']})
```

**Comment by odysseaspapadimas** [comment]
> I think Webpack patches `process` with the custom env variables. The solution might be to have the plugin not override it.
> 
> Does this work?
> 
> ```js
> new NodePolyfillPlugin({excludeAliases: ['process']})
> ```

Yes this works! Unfortunately it's not the source of my original problem, but still thank you so much!
