### ISSUE TITLE
Seperate presets for maximum compatibility and convenience

### ISSUE THREAD

**Issue by Richienb** [Richienb/node-polyfill-webpack-plugin#50]
One preset will be *as if* webpack never removed the feature, and another preset (the new default) will remove all the polyfills that have no practical purpose (#44. #20), setting mostly everything else that is yet to be polyfilled as no-ops (#41). - biggest change is noticable for the globals.

**Comment by Richienb** [comment]
@afonsojramos thoughts?

**Comment by afonsojramos** [comment]
Don't really see a need for it. What I would do is add the `fs` module, remove the `console` one since we have it in the browser and regarding #44, I think it is user error, because why would you need to add the polyfills if you are running on a Node env?

**Comment by Richienb** [comment]
> What do you think of accepting an argument that defines which modules should not be polyfilled?

This is already an option called `excludeAliases`.

> I suppose that most people want as much as they can, and, if they don't want them, they can just disable them manually.

I don't think so. People in the past have gotten confused by what they thought were polyfills which actually turned out to be shims. So, I want to make it obvious what isn't supported.

**Comment by afonsojramos** [comment]
However, this package doesn't even have `fs` fallback, so setting it as false definitely helps and enhances the usability of this package. Please reconsider #45.

**Comment by Richienb** [comment]
Closing because we ended up deviating from the Webpack polyfills, such that it is no longer technically a 1:1 backwards compatible switch. Despite this, there has somehow been no issue.
