### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by obi-awyss** [Richienb/node-polyfill-webpack-plugin#51]
This is currently not being polyfilled:

`timersPromises.setImmediate([value[, options]])`

https://nodejs.org/api/timers.html#timers_setimmediate_callback_args

**Comment by muskilh** [comment]
> This is currently not being polyfilled:
> 
> `timersPromises.setImmediate([value[, options]])`
> 
> https://nodejs.org/api/timers.html#timers_setimmediate_callback_args

I ran into this too,  you can solve it with this as `timers` is polyfilled:
```
var timers = require('timers');
timers.setImmediate(...);
```
From: https://github.com/browserify/browserify/issues/985#issuecomment-62906320

and if you need to use it as just `setImmediate()` you can do something like this:
https://github.com/browserify/browserify/issues/985#issuecomment-62963011
