### ISSUE TITLE
Remove `punycode` polyfill

### ISSUE THREAD

**Issue by tre2man** [Richienb/node-polyfill-webpack-plugin#52]
The funycode seems to be deprecated.

```
(node:43949) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

**Comment by Richienb** [comment]
This is a problem with your code: your code is importing the `punycode` module, which is deprecated.

Instead, install the similarly named [`punycode` userland module](https://github.com/mathiasbynens/punycode.js) from npm and import it like `require('punycode/')`, noting the forward slash (`/`).

**Comment by Richienb** [comment]
I think it is worth stopping polyfilling `punycode` since there is no practical use to have it there now. (maybe time to separate out into compat- and recommended- configs)?
