### ISSUE TITLE
LIcense change of dependency domain-browser

### ISSUE THREAD

**Issue by thomasballinger** [Richienb/node-polyfill-webpack-plugin#55]
https://github.com/Richienb/node-polyfill-webpack-plugin/commit/4d26fb0ed91da50c2f66994e0905bcdc44c34306 a few months ago updated [domain-browser](https://github.com/bevry/domain-browser) semver range from ^4.22.0 to ^5.7.0. 4.22 was the last release of domain-browser licensed MIT; the library is [now licensed under the Artistic License](https://github.com/bevry/domain-browser/commit/e40ec3d274ff42bb1dc7762b0698a1a21a12e17e).

This is a small library with no dependencies, any interest in vendoring the 60 lines of [the last version published under MIT](https://github.com/bevry/domain-browser/blob/8bce7f4a093966ca850da75b024239ad5d0b33c6/source/index.js)?

**Comment by mistic** [comment]
@Richienb I think this is a good idea. The Artistic License could be problematic when used in open source projects that mostly rely on MIT licenses. I've came up into that problem as well and for now I've reverted to the `v3.0.0` of this plugin because of that.

**Comment by Richienb** [comment]
It seems be compatible, but not sure https://interoperable-europe.ec.europa.eu/licence/compare/Artistic-2.0;MIT

I have asked: https://opensource.stackexchange.com/questions/15199/can-i-use-an-artistic-license-2-0-library-in-a-mit-license-library

**Comment by Richienb** [comment]
Downgraded.
